title: "Manus et Machina"
timezone: UTC
baseurl: ""  # Change to "/your-repo-name" if necessary
permalink: "/:slug/"
favicon: "assets/images/favicon.ico"
author: Shatha
paginate: 30
future: true  # Allow posts dated in the future to appear
disqus: "demowebsite"
locale: "en_us"
lang: "en_us"
feed_items: 10
feed_update_period: "daily"
feed_update_frequency: 1
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    disable: true

sass:
  sass_dir: _sass
  style: compressed

ganalytics: "UA-113961478-1"

# Authors
authors:
 Shatha:
    name: "Shatha"
    display_name: "Shatha"
    avatar: "assets/images/sal.png"
    email: "sma9158@nyu.edu"
    web: "https://www.wowthemes.net/category/jekyll-themes/"
    twitter: "https://twitter.com/wowthemesnet"
    description: "Sophomore at NYUAD, willing to learn every day."

# Social Links
social:
  instagram: "https://www.instagram.com/bootstrapstarter/"
  facebook: "https://www.facebook.com/bootstrapstartercom-346329609045284"
  twitter: "https://twitter.com/bstartercom"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Force rebuild trick (small change)
force_rebuild: true  # <<<<< ADD THIS

